-- Calculate total revenue generated by each product in each year and also for all years
SELECT p.Product_ID, YEAR(STR_TO_DATE(o.Order_Date, '%d/%m/%Y')) AS Order_Year, SUM(p.cart_quantity * p.price) AS Total_Revenue
FROM Product p
JOIN contains_ c ON p.product_id = c.product_id
JOIN order_ o ON c.order_id = o.order_id
WHERE o.order_status = 'shipped'
GROUP BY Order_Year,p.product_id WITH ROLLUP
ORDER BY p.product_id, Order_Year DESC;

-- Revenue generated each month with total orders in that particular month wrt particular customer
SELECT 
MONTH(STR_TO_DATE(o.Order_Date, '%d/%m/%Y')) AS Month_,
o.Customer_ID, 
SUM(p.cart_quantity * p.price) AS Total_Revenue,
COUNT(distinct o.Order_ID) AS Total_Orders
FROM 
order_ o
JOIN contains_ c ON c.Order_ID = o.Order_ID
JOIN product p ON p.Customer_ID = o.Customer_ID

WHERE o.Order_Status = 'shipped'
GROUP BY 
Month_, customer_id WITH ROLLUP
ORDER BY 
Month_, Customer_ID;
  
-- Payment Amount Rollup by Method and Status, Including Subtotal and Grand Total  
SELECT p.Order_ID, SUM(pr.Price * pr.Cart_Quantity) AS Amount, p.Payment_Status, p.Method
FROM payment p
JOIN order_ o ON p.Order_ID = o.Order_ID
JOIN contains_ c ON o.Order_ID = c.Order_ID
JOIN product pr ON c.Product_ID = pr.Product_id
GROUP BY p.Payment_Status, p.Method, p.Order_ID WITH ROLLUP;

-- Find the total of each customer who has purchased products supplied by a supplier with the ID 1 and paid using the method "Credit Card"
SELECT c.Full_Name, SUM(p.Price * p.Cart_Quantity) as Total
FROM customer c
INNER JOIN order_ o ON c.Customer_ID = o.Customer_ID
INNER JOIN contains_ co ON o.Order_ID = co.Order_ID
INNER JOIN product p ON co.Product_ID = p.Product_id
INNER JOIN supplies s ON p.Product_id = s.Product_ID
INNER JOIN supplier su ON s.Supplier_ID = su.Supplier_ID
INNER JOIN payment pm ON o.Order_ID = pm.Order_ID
WHERE su.Supplier_ID = 1 AND pm.Method = "Credit Card"
GROUP BY c.Customer_ID ;
